# Generated by Django 4.1.2 on 2023-06-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_privacypolicy_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="otp_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name="privacypolicy",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="termsandconditions",
            name="content",
            field=models.TextField(),
        ),
    ]
