# Generated by Django 4.1.2 on 2023-06-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_remove_profile_otp_code_alter_privacypolicy_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="otp",
            field=models.CharField(default=123456, max_length=6),
        ),
    ]
