# Generated by Django 4.1.2 on 2023-06-20 11:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_profile_otp_expiry_time_alter_profile_otp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="otp_expiry_time",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
