# Generated by Django 4.1.2 on 2023-06-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_profile_otp_expiry_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="otp",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
