# Generated by Django 4.1.2 on 2023-06-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_alter_profile_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
